sudo: false
language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - 'iojs'
  - '0.12'
  - '0.10'
  - '0.8'
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" == "0.8" ]; then npm install -g npm@latest-2; fi'
